Hw8 db
tromian/AFProject pull request #10
Opened 2021-06-17 15:53 UTC by tromian

2021-06-20 09:14 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/db/MoviesDB.kt
> +            synchronized(lock) {
Вопросы на подумать:
1) Что изменится, если написать вместо `synchronized(lock) {`: (синтаксис пишу по памяти, примерно так)
а) `synchronized {`
b) `synchronized(this) {`
c) `synchronized(MoviesDB::getClass) {`
d) @Synchronized fun getInstance(...)...

2) Как устроен внутри `by lazy{}` (как он компилируется в Java Bytecode)? Есть ли там потокобезопасность?

2021-06-20 09:16 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/db/entityes/MovieEntity.kt
> -    val isLiked: Boolean? = null,
`- val isLiked: Boolean? = null`
Представь, что твой апп уже был у пользователей с этой колонкой в DB
Что произойдет при апдейте аппа?
Что нужно сделать, чтобы этого не произошло?

2021-06-20 09:17 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/network/tmdbapi/ResponseWrapper.kt
> +        } else return Resource.Error(apiMethod.message())
а зачем тут return внес внутрь ифов?

2021-06-20 09:20 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +            return when (result) {
тоже return-ы расплодились

2021-06-20 09:21 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +        }
```
val entities = mutableListOf<MovieEntity>;()
movies.forEach { movie ->
    entities.add(fromMovieToMovieEntity(movie))
}
```
А зачем так сложно? 
Можно же заюзать map функцию внутри insertMovies

2021-06-20 09:23 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +    }
not important: можно вместо функции в репозитории cделать standalone (вне класса) extension функцию
`fun GenreEntity.toGenre(): Genre {...}`
и положить ее в файл с GenreEntity

2021-06-20 09:23 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +    }
то же самое для остальных маппер функций

2021-06-20 09:24 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +    }
тебе тогда не нужен будет инстанс репозитория, чтобы смаппить одну модель в другую

2021-06-20 09:24 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/MainActivity.kt
> +    var repository: MoviesDataRepository? = null
`var repository: MoviesDataRepository? = null`

а зачем убрал lateinit тут?

2021-06-20 09:26 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentMoviesDetails.kt
> +        }
```
(activity as MainActivity).repository?.let {
            repository = it
        }
```
вот тут как раз уместно сделать repository nullable вместо lateinit
после такой инициализации вполне возможно, что он не заассайнится

2021-06-20 09:31 UTC, phansier requested changes
В целом хорошо, несколько замечаний нужно подумать или поправить

2021-06-20 09:31 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentMoviesList.kt
> +        if (viewModel == null){
`if (viewModel == null){`
сколько раз у текущего инстанса фрагмента вызовется onViewCreated?
Возможно ли, что этот кусок с присваиванием будет вызван два раза?
Если нет - зачем менять lateinit на nullable?

2021-06-20 09:31 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentMoviesList.kt
> +        if (viewModel == null){
Лучше по возможности всегда использовать ненуллабельные переменные, если ты уверен, что они будут присвоены asap

2021-06-20 09:31 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentMoviesList.kt
> +        if (viewModel == null){
иначе возникает слишком много let-ов по коду и проверок на null для любого чиха

2021-06-20 09:31 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/viewmodels/MoviesViewModel.kt
> +        val localData: List<Movie> = withContext(Dispatchers.IO){
`withContext(Dispatchers.IO){`
а зачем, если у тебя уже текущий контекст выполняется в Dispatchers.IO ?

2021-06-22 10:32 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/db/MoviesDB.kt
> +            synchronized(lock) {
Готово, разобрался.

2021-06-22 10:50 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/network/tmdbapi/ResponseWrapper.kt
> +        } else return Resource.Error(apiMethod.message())
поправил

2021-06-22 10:55 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +            return when (result) {
тоже поправил

2021-06-22 11:04 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/view/MainActivity.kt
> +    var repository: MoviesDataRepository? = null
Смотрел видео Кирилла что ведет Android Broadcast, он говорит что нулабельность это нормальное состояние и что если возможен нулл то лучше обьявить об этом явно, поэтому так и сделал.

2021-06-22 12:04 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentMoviesList.kt
> +        if (viewModel == null){
onViewCreated вызывается каждый раз когда становится активным фрагмент. Сделал вьюмодель лейтинит, но перед этим сделал инициализацию через ViewModelProvider, до этого просто создавал класс вьюмодели и проверял ссылку на нулл чтоб не создавался новый инстанс.

2021-06-24 09:49 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/db/entityes/MovieEntity.kt
> -    val isLiked: Boolean? = null,
Миграцию прописать в классе Бд

2021-06-24 11:44 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +    }
Вынес все мапперы в отдельный файл кроме одной, там ещё хранение категорий не реализовано как надо.

2021-06-24 11:54 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +        }
Заюзал

2021-06-24 16:16 UTC, merged