Search and Save Movie
tromian/AFProject pull request #11
Opened 2021-07-21 11:15 UTC by tromian

2021-07-24 09:51 UTC, phansier requested changes
В целом уже хорошо)
Все комменты не критичные - но лучше поправить

2021-07-24 09:51 UTC, phansier commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
`    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"`
какая сейчас версия котлин? если меньше 1.5.0 - попробуй обновиться
начиная с 1.5.0 не нужно явно  stdlib подключать - если подключен kotlin плагин

2021-07-24 09:51 UTC, phansier commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
`implementation 'androidx.legacy:legacy-support-v4:1.0.0'`
для чего тащим? нужно четко понимать, когда затаскиваешь новую зависимость, для чего она нужна и какие проблемы может вызвать
конкретно  androidx.* проблем вызвать не должны, но общее правило для зависимостей

2021-07-24 09:51 UTC, phansier commented on app/build.gradle
> +    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.3'
`kotlinx-coroutines-android:1.4.3'`
вместе с версией котлин можно тоже попробовать приподнять до 1.5.*

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/network/responses/SearchResponse.kt
> +@Serializable
тут какая-то смесь из двух библиотек
ты для сериализации используешь Gson или kotlinx.Serialization?
неиспользуемую нужно убрать вместе с ее аннотациями

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +    override suspend fun searchMovie(title: String): List<Movie> {
название не оч понятное
вообще с помощью названий функций можно делать код в целом понятнее, чтобы не добавлять комменты
что делает эта функция? если она идет в апи с какой-то строкой и ищет все фильмы, названия которых ее содержат, то имеет смысл назвать что-то типа:
`fun searchMoviesByTitleInApi()`

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/domain/repository/MoviesRepository.kt
> +    suspend fun nowPlaying(page : Int): List<Movie>
`fun nowPlaying(page : Int)`
то же самое
надо подумать над названием, стороннему разработчику (из другой команды например) будет совсем не понятно, причем тут page

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentFavourite.kt
> +class FragmentFavourite : Fragment(R.layout.fragment_favourite_movies) {
not important: правильнее Favorite

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentFavourite.kt
> +        findNavController().navigate(R.id.fragment_details,bundle)
можно проще через navArgs
https://developer.android.com/codelabs/android-navigation#7

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentMoviesDetails.kt
> +    }
```
override fun onDestroy() {
        super.onDestroy()
    }
```
зачем?

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentSearch.kt
> +            repository = it
лучше не делать `var repository` в фрагменте - он у тебя используется только чтобы создать ViewModel и так будет меньше шансов использовать его напрямую без ViewModel

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/holders/MovieViewHolder.kt
> +        }
not important:
можно короче написать:
```
liked.setImageResource(if (movie.isLiked)R.drawable.ic_heart_liked else R.drawable.ic_heart)
```

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/viewmodels/MovieSearchVM.kt
> +        delay(2_000)
`delay(2_000)` - это что-то для тестирования было?

2021-07-24 09:51 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/viewmodels/MoviesViewModel.kt
> +    var page: Int = 1
а зачем page нужен и как он меняется?

2021-07-24 09:51 UTC, phansier commented on app/src/main/res/layout/fragment_main_list.xml
> +    xmlns:tools="http://schemas.android.com/tools"
зачем тут пустой фрагмент?

2021-07-24 10:15 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentMoviesDetails.kt
> +    }
Удалил пока, у меня там где то мемори лик который пока не нашел)

2021-07-24 10:16 UTC, tromian commented on app/src/main/res/layout/fragment_main_list.xml
> +    xmlns:tools="http://schemas.android.com/tools"
Он для чего то был видимо нужен, отправляется на свалку.

2021-07-24 10:16 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/viewmodels/MoviesViewModel.kt
> +    var page: Int = 1
пока не меняется, но будет

2021-07-24 10:18 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/viewmodels/MovieSearchVM.kt
> +        delay(2_000)
Да, не в там задержку вставил, её надо в обработчик поисковой вью запихнуть

2021-07-24 10:32 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +    override suspend fun searchMovie(title: String): List<Movie> {
Сделал методы в репозитории понятнее.

2021-07-24 10:56 UTC, tromian commented on app/build.gradle
> +    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
У меня уже 1.5.21, удалил подключение

2021-07-24 11:01 UTC, tromian commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Это тоже убрал

2021-07-24 11:08 UTC, tromian commented on app/build.gradle
> +    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.3'
Поднял до 1.5.1 вроде ничего не сломалось)

2021-07-25 08:59 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/network/responses/SearchResponse.kt
> +@Serializable
Убрал котлина сериализацию, как то в начале втулил не задумываясь, оставил Gson только потому что он работает, и с настройками конфигурации Json самостоятельно пока не разобрался нормально.

2021-07-25 09:02 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentFavourite.kt
> +class FragmentFavourite : Fragment(R.layout.fragment_favourite_movies) {
+

2021-07-25 09:02 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/domain/repository/MoviesRepository.kt
> +    suspend fun nowPlaying(page : Int): List<Movie>
+

2021-07-25 11:37 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentFavourite.kt
> +        findNavController().navigate(R.id.fragment_details,bundle)
Сделал как мне кажется теперь по нормальному)

2021-07-25 11:46 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentMoviesDetails.kt
> +        movie = safeArgs.movie//arguments?.getSerializable("movie") as Movie
коммент остался

2021-07-25 11:47 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentSearch.kt
> +            repository = it
этот остался

2021-07-25 11:48 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/viewmodels/MovieSearchVM.kt
> +        delay(2_000)
а зачем в начало? у тебя каждый раз запрос будет на 2сек дольше проходить

2021-07-25 11:48 UTC, phansier commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-serialization:1.5.21"
остался         classpath "org.jetbrains.kotlin:kotlin-serialization:1.5.21"
и коммент

2021-07-25 11:48 UTC, phansier approved these changes

2021-07-25 12:11 UTC, phansier approved these changes

2021-07-25 12:42 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentSearch.kt
> +            repository = it
Вынесено создание в обьект DI

2021-07-25 12:58 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/viewmodels/MovieSearchVM.kt
> +        delay(2_000)
Изменил подход к этой фиче по поиску, теперь момент запроса контролируется во фрагменте.

2021-07-25 13:02 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/FragmentMoviesDetails.kt
> +        movie = safeArgs.movie//arguments?.getSerializable("movie") as Movie
Убрал

2021-07-25 13:02 UTC, tromian commented on build.gradle
> +        classpath "org.jetbrains.kotlin:kotlin-serialization:1.5.21"
Убрал

2021-07-25 13:03 UTC, tromian reviewed
-

2021-07-25 13:06 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/view/fragments/holders/MovieViewHolder.kt
> +        }
Поправил

2021-07-25 13:10 UTC, merged