Homework3
tromian/AFProject pull request #2
Opened 2020-11-28 09:52 UTC by tromian

2020-11-28 11:17 UTC, phansier requested changes

2020-11-28 11:17 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/FragmentMoviesList.kt
> +        return inflater.inflate(R.layout.fragment_movies_list, container, false)
Можно через конструктор

2020-11-28 11:17 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/MainActivity.kt
> +            supportFragmentManager.findFragmentByTag(FRAGMENT_TAG) as FragmentMoviesList
А это зачем?

2020-11-28 11:17 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/MainActivity.kt
> +                .addToBackStack(null)
почему `.addToBackStack(null)`?

2020-11-28 11:17 UTC, phansier commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="wrap_content"/>
а зачем вложенный FrameLayout?

2020-11-28 11:17 UTC, phansier commented on app/src/main/res/layout/activity_movie_details.xml
>          <TextView
Хорошо бы обработать нажатие на back в интерфейсе

2020-11-28 11:17 UTC, phansier commented on app/src/main/res/layout/fragment_movies_details.xml
> +        layout="@layout/activity_movie_details"
А зачем так?
В задании же переименовать надо было просто layout-файл.

2020-11-28 11:17 UTC, phansier commented on app/src/main/res/layout/layout_movies_preview.xml
> +    android:background="#222232"
вынеси в colors

2020-11-28 11:17 UTC, phansier commented on app/src/main/res/layout/fragment_movies_list.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
в горизонтальной ориентации карточка фильма не помещается
можно обернуть в ScrollView

2020-11-28 11:18 UTC, phansier requested changes
В целом хорошо, но нужно доделать

2020-11-29 12:19 UTC, phansier commented
Еще увидел сердечко на карточке в списке и края у карточки должны быть закруглены

2020-11-29 15:20 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/MainActivity.kt
> +            supportFragmentManager.findFragmentByTag(FRAGMENT_TAG) as FragmentMoviesList
Для того чтоб восстанавливать фрагмент при повороте экрана после пересоздания активити.

2020-11-29 15:20 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/MainActivity.kt
> +                .addToBackStack(null)
Добавил чтобы обрабатывать переход назад к предыдущему (главному) фрагменту, без этого действия приложение бы просто закрывалось, в параметрах без имени этой транзакции потому что на данный момент нет необходимости обрабатывать переход к этой конкретной транзакции.

2020-11-29 16:02 UTC, tromian commented on app/src/main/res/layout/fragment_movies_list.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Поправил

2020-11-29 16:02 UTC, tromian commented on app/src/main/res/layout/layout_movies_preview.xml
> +    android:background="#222232"
Поправил

2020-11-29 16:02 UTC, tromian commented on app/src/main/res/layout/fragment_movies_details.xml
> +        layout="@layout/activity_movie_details"
Поправил

2020-11-29 16:02 UTC, tromian commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="wrap_content"/>
Поправил

2020-11-29 16:02 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/FragmentMoviesList.kt
> +        return inflater.inflate(R.layout.fragment_movies_list, container, false)
Поправил

2020-11-29 16:16 UTC, tromian commented on app/src/main/res/layout/activity_movie_details.xml
>          <TextView
Нажатие тоже обработал.

2020-11-29 21:35 UTC, phansier approved these changes
Можно сердце оставить только в векторном формате + не использовать @android:color/white
Остальное всё хорошо

2020-12-08 07:29 UTC, merged