Hw7 net
tromian/AFProject pull request #7
Opened 2021-04-12 09:50 UTC by tromian

First  implementation  working with Api

2021-04-20 07:13 UTC, phansier approved these changes

2021-04-20 07:13 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/model/data/JsonActor.kt
> +    val cast_id: Int,
если kebab_case выносишь в Serialized, то сами поля можно уже по обычной нотации именовать

2021-04-20 07:13 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/model/models/Genre.kt
> +}
очень плохо читается код в таком виде
или можно в студии включить автоформатирование при коммите, или (что еще лучше) - подрубить на встроенный в Github CI статический анализатор Detekt, который не даст неотформатированный код запушить в мастер

2021-04-20 07:13 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/model/repository/BaseRepository.kt
> +    fun <T> safeApiResponse(apiMethod: Response<T>) : Resource<T> {
кажется, что излишне ради одного утилитного класса раздувать наследование с BaseRepository
тем более, что ему ничего не нужно от этого класса
можно спокойно сделать эту функцию без класса вообще, либо положить в object (сделать аналог статической функции в Java)

2021-04-20 07:13 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/model/repository/MoviesRepository.kt
> +                        imageUrl = AppConstants.POSTER_URL + AppConstants.POSTER_SIZE +it.posterPath,
лучше `AppConstants.POSTER_URL + AppConstants.POSTER_SIZE +it.posterPath` вынести в отдельный метод

2021-04-20 07:13 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/model/repository/MoviesRepository.kt
> +                        pgAge = if (it.adult == true) 16 else 13,
и `if (it.adult == true) 16 else 13` - тоже, это по сути уже часть бизнес логики, которая может меняться со временем

2021-04-20 07:14 UTC, phansier commented
Я бы еще немного переложил файлы между пакетами и повыделял интерфейсы у репозитория, но это мб мне Clean Architecture уже везде хочется втащить)

2021-04-21 12:21 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/model/data/JsonActor.kt
> +    val cast_id: Int,
Исправил

2021-04-21 12:38 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/model/repository/MoviesRepository.kt
> +                        pgAge = if (it.adult == true) 16 else 13,
Вынес значения возраста в константы приложения

2021-04-21 12:39 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/model/repository/MoviesRepository.kt
> +                        imageUrl = AppConstants.POSTER_URL + AppConstants.POSTER_SIZE +it.posterPath,
Вынес получения ссылки в отдельные методы для постера и изображения актера

2021-04-27 11:21 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/model/models/Genre.kt
> +}
Изменил список id в модели на строку, значения которой составляется при формировании обьекта в репозитории.

2021-04-27 11:22 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/model/repository/BaseRepository.kt
> +    fun <T> safeApiResponse(apiMethod: Response<T>) : Resource<T> {
Избавился от наследования, создав обьект для обертки ответа от сети.

2021-05-29 13:20 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/network/tmdbapi/ResponseWrapper.kt
> +            Resource.Success(apiMethod.body()!!)
`apiMethod.body()!!` может привести к крашу в рантайме

2021-05-29 13:22 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +        }
нехорошо делать запросы при инициализации
лучше вынести в метод init() и дергать его явно
зачем это нужно? представь что у тебя в аппе две фичи:
1) загрузка фильмов
2) кулинарные рецепты

Пользователь может теоретически работать только с рецептами и лишние загрузки фильмов ему не очень то нужны, пока он явно не зайдет в тот раздел. Или другая бизнес-логика по фетчингу этих жанров.
Конструктор же не управляется бизнес-логикой (метод init() может)

2021-05-29 13:26 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +            is Resource.Success -> result.data.genres!!.map {
`result.data.genres!!` опять потенциальный источник крашей

2021-05-29 13:26 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +            is Resource.Success -> result.data.genres!!.map {
посмотри прям по коду !! и исправь везде

2021-05-29 13:27 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +                        genres = it.genreIds?.let { it1 -> loadGenres(it1) },
`it.genreIds?.let { it1 -> loadGenres(it1)`
it1 можно же более понятно назвать (+ ниже тоже)

2021-05-29 13:28 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +    private fun loadGenres(genreIds: List<Int>): String {
мб loadGenres() сделать suspend и в ней делать загрузку с сервера?

2021-05-29 13:29 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +    private fun loadGenres(genreIds: List<Int>): String {
и почему он просто стрингу возвращает? как она потом используется?

2021-05-29 14:31 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/domain/models/Actor.kt
> +        val id: Int? = null,
это же уже доменная модель
зачем нам тут актер без id или имени
скорее всего мы хотим уже полностью заполненную и валидную модельку на этом слое

2021-05-29 14:31 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/domain/models/Actor.kt
> +        val id: Int? = null,
по остальным моделям в этом слое тоже нужно пройтись

2021-05-29 14:33 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/view/adapters/ActorsListAdapter.kt
> +            Log.d(TAG, actor.name.toString())
nice to have comment: можно попробовать втащить [Timber](https://github.com/JakeWharton/timber) для логирования
он дает более структурированные логи

2021-05-29 14:35 UTC, phansier commented on app/src/main/java/com/tromian/game/afproject/presentation/viewmodels/MoviesViewModel.kt
> +       val app : Application,
`val app : Application,`
а зачем тут прям целый Application
нужен ApplicationContext?

2021-05-29 14:42 UTC, phansier requested changes
См комменты.
Предлагаю после их фикса залить все в мастер и пнуть меня: посмотрю уже более архитектурно в студии и с запуском приложения

2021-05-30 09:00 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +            is Resource.Success -> result.data.genres!!.map {
Добавил проверку на null перед парсингом данных из успешного ответа. Теперь как и в случае неуспешного ответа если данные отсутствуют методы возвращают пустой список.

2021-05-30 09:01 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/data/repository/MoviesDataRepository.kt
> +                        genres = it.genreIds?.let { it1 -> loadGenres(it1) },
Заменил на явное название

2021-05-30 09:13 UTC, tromian commented on app/src/main/java/com/tromian/game/afproject/presentation/view/adapters/ActorsListAdapter.kt
> +            Log.d(TAG, actor.name.toString())
Уже не актуально в этом классе, удалил вообще, добавлял на время. Ссылку на эту библиотеку сохранил, как понадобится следующий раз логировать то заюзаю.

2021-05-30 12:17 UTC, tromian reviewed
Исправил места где использовал !! на проверки на null

2021-05-30 12:32 UTC, merged